name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: HenriSM07
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit e push do SVG
        uses: EndBug/add-and-commit@v9
        with:
          message: "Atualizando Snake SVG"
          add: "dist/github-contribution-grid-snake.svg"

      - name: Publicar SVG no branch `output`
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout --orphan output
          git --work-tree=dist add --all
          git --work-tree=dist commit -m "Deploy snake"
          git push origin output --force
